import 'package:cashback/core/constants/image_constants.dart';
import 'package:flutter/material.dart';

const List<String> turkishCities = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkâri",
  "Hatay",
  "Isparta",
  "Mersin",
  "Iğdır",
  "İstanbul",
  "İzmir",
  "Karabük",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kilis",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Karaman",
  "Kırıkkale",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Şırnak",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",
];

List<Map<String, String>> helpItems = [
  {
    "leading": ImageConstants.helpBus,
    "title": "Otobüs Bileti",
  },
  {
    "leading": ImageConstants.plane,
    "title": "Uçak Bileti",
  },
  {
    "leading": ImageConstants.hotel,
    "title": "Otel",
  },
  {
    "leading": ImageConstants.ship,
    "title": "Feribot Bileti",
  },
];

final profileItems = [
  {
    "title": "Seyahatlerim",
    "icon": const Icon(Icons.airplanemode_active),
  },
  {
    "title": "Kampanyalarım",
    "icon": const Icon(Icons.card_giftcard_outlined),
  },
  {
    "title": "Alarmlarım",
    "icon": const Icon(Icons.notifications_none_outlined),
  },
  {
    "title": "Profilim",
    "icon": const Icon(Icons.person_outline_outlined),
  },
  {
    "title": "Yardım",
    "icon": const Icon(Icons.help_outline),
  },
  {
    "title": "Ayarlar",
    "icon": const Icon(Icons.settings_outlined),
  },
  {
    "title": "Hakkımzda",
    "icon": const Icon(Icons.info_outline),
  },
];
